### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by arthurbrazil** [aarmora/jordan-scrapes-real-foreclose#4]
Hello thanks for this great work! I was destroying myself creating this exact same implementation. I am having some strange behavior.
It does not seem to be picking up all of the auctions in my selected area, which is Hillsborough.

`> jordan-scrapes-realforeclose@1.0.0 start C:\Users\*****\Desktop\jordan-scrapes-real-foreclose-master
> tsc && node ./dist/index.js

Finished checking day: 11/22/2021 Total auctions now: 0
Finished checking day: 11/23/2021 Total auctions now: 0
Finished checking day: 11/24/2021 Total auctions now: 0
Finished checking day: 11/29/2021 Total auctions now: 0
Finished checking day: 11/30/2021 Total auctions now: 0
Finished checking day: 12/01/2021 Total auctions now: 0
Finished checking day: 12/02/2021 Total auctions now: 0
Finished checking day: 12/03/2021 Total auctions now: 11
Finished checking day: 12/06/2021 Total auctions now: 11
Finished checking day: 12/07/2021 Total auctions now: 11
Finished checking day: 12/08/2021 Total auctions now: 11
Finished checking day: 12/09/2021 Total auctions now: 11
Finished checking day: 12/10/2021 Total auctions now: 22
Finished checking day: 12/14/2021 Total auctions now: 22
Finished checking day: 12/15/2021 Total auctions now: 22
Finished checking day: 12/16/2021 Total auctions now: 22
Finished checking day: 12/17/2021 Total auctions now: 22
Finished checking day: 12/20/2021 Total auctions now: 22
Finished checking day: 12/22/2021 Total auctions now: 22
Finished checking day: 12/27/2021 Total auctions now: 22
Finished checking day: 12/28/2021 Total auctions now: 22
Finished checking day: 12/29/2021 Total auctions now: 22
Finished checking day: 12/30/2021 Total auctions now: 22
Total auctions 22`

**Comment by arthurbrazil** [comment]
same issue when trying pasco as the region

**Comment by aarmora** [comment]
@arthurbrazil I pushed and update that fixes things...I think. I didn't overly test it.

Can you check and see if it works for you?

**Comment by arthurbrazil** [comment]
It is now reading the auctions correctly but seems to be sometimes doubling up. Also had an error along the way. The csv file is also reflecting double entries. Thanks for maintaining this repo. I will be using it to study your execution.
```
> jordan-scrapes-realforeclose@1.0.0 start C:\Users\*******\Desktop\jordan-scrapes-real-foreclose-master
> tsc && node ./dist/index.js

testing closed auctions 0
Total auctionsHandle 8
Total auctionsHandle 8
Finished checking day: 11/22/2021 Total auctions now: 16
testing closed auctions 0
Total auctionsHandle 7
Total auctionsHandle 7
Finished checking day: 11/23/2021 Total auctions now: 30
testing closed auctions 0
Total auctionsHandle 3
Total auctionsHandle 3
Finished checking day: 11/24/2021 Total auctions now: 36
No closed auctions found
Total auctionsHandle 4
Finished checking day: 11/29/2021 Total auctions now: 40
testing closed auctions 0
Total auctionsHandle 4
Total auctionsHandle 4
Finished checking day: 11/30/2021 Total auctions now: 48
testing closed auctions 0
Total auctionsHandle 8
Total auctionsHandle 8
Finished checking day: 12/01/2021 Total auctions now: 64
testing closed auctions 0
Total auctionsHandle 9
Total auctionsHandle 9
Finished checking day: 12/02/2021 Total auctions now: 82
testing closed auctions 0
Total auctionsHandle 11
Total auctionsHandle 11
Total auctionsHandle 4
Finished checking day: 12/03/2021 Total auctions now: 108
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/06/2021 Total auctions now: 109
testing closed auctions 0
Total auctionsHandle 4
Total auctionsHandle 4
Finished checking day: 12/07/2021 Total auctions now: 117
testing closed auctions 0
Total auctionsHandle 1
No waiting auctions found TimeoutError: waiting for selector ".Head_W .PageRight:nth-of-type(3)" failed: timeout 1500ms exceeded
odules\puppeteer\lib\DOMWorld.js:432:17)    at Frame.waitForSelector (C:\Users\******\Desktop\jordan-scrapes-real-foreclose-master\node_modules\puppeteer\lib\FrameManager.js:627:47)    at Frame.<anonymous> (C:\Users\******\Desktop\jordan-scrapes-real-foreclose-master\node_modules\puppeteer\lib\helper.js:112:23)    at Page.waitForSelector (C:\Users\******\Desktop\jordan-scrapes-real-foreclose-master\node_modules\puppeteer\lib\Page.js:1095:29)    at C:\Users\******\Desktop\jordan-scrapes-real-foreclose-master\dist\index.js:86:24
    at Generator.next (<anonymous>)    at fulfilled (C:\Users\******\Desktop\jordan-scrapes-real-foreclose-master\dist\index.js:5:58)  
Finished checking day: 12/08/2021 Total auctions now: 118testing closed auctions 0
Total auctionsHandle 9
Total auctionsHandle 9
Finished checking day: 12/09/2021 Total auctions now: 136
testing closed auctions 0
Total auctionsHandle 11
Total auctionsHandle 11
Total auctionsHandle 2
Finished checking day: 12/10/2021 Total auctions now: 160
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/14/2021 Total auctions now: 161
No closed auctions found
Total auctionsHandle 3
Finished checking day: 12/15/2021 Total auctions now: 164
No closed auctions found
Total auctionsHandle 2
Finished checking day: 12/16/2021 Total auctions now: 166
No closed auctions found
Total auctionsHandle 5
Finished checking day: 12/17/2021 Total auctions now: 171
testing closed auctions 0
Total auctionsHandle 7
Total auctionsHandle 7
Finished checking day: 12/20/2021 Total auctions now: 185
No closed auctions found
Total auctionsHandle 2
Finished checking day: 12/22/2021 Total auctions now: 187
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/27/2021 Total auctions now: 188
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/28/2021 Total auctions now: 189
No closed auctions found
Total auctionsHandle 2
Finished checking day: 12/29/2021 Total auctions now: 191
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/30/2021 Total auctions now: 192
Total auctions 192
```

**Comment by arthurbrazil** [comment]
Also, not sure if intended behavior but case number is scraping the html instead of the text of the case number.

**Comment by aarmora** [comment]
Okay, try that.

![First try](https://media.giphy.com/media/II1qZZrMcWJ0s/giphy.gif)

**Comment by arthurbrazil** [comment]
That seems to be working. I will include my console for you to see. It is still double logging some of them but they are unique in the output file. Thanks again for maintaining. Also on a side note, The default in the documentation is miami but in the release file it is Hillsborough and may lead to some confusion. 

```
> jordan-scrapes-realforeclose@1.0.0 start C:\Users\******\Desktop\jordan-scrapes-real-foreclose-master
> tsc && node ./dist/index.js

testing closed auctions 0
Total auctionsHandle 7
Total auctionsHandle 7
Finished checking day: 11/23/2021 Total auctions now: 7
testing closed auctions 0
Total auctionsHandle 3
Total auctionsHandle 3
Finished checking day: 11/24/2021 Total auctions now: 10
No closed auctions found
Total auctionsHandle 4
Finished checking day: 11/29/2021 Total auctions now: 14
testing closed auctions 0
Total auctionsHandle 4
Total auctionsHandle 4
Finished checking day: 11/30/2021 Total auctions now: 18
testing closed auctions 0
Total auctionsHandle 8
Total auctionsHandle 8
Finished checking day: 12/01/2021 Total auctions now: 26
testing closed auctions 0
Total auctionsHandle 9
Total auctionsHandle 9
Finished checking day: 12/02/2021 Total auctions now: 35
testing closed auctions 0
Total auctionsHandle 11
Total auctionsHandle 11
Total auctionsHandle 4
Finished checking day: 12/03/2021 Total auctions now: 42
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/06/2021 Total auctions now: 42
testing closed auctions 0
Total auctionsHandle 4
Total auctionsHandle 4
Finished checking day: 12/07/2021 Total auctions now: 44
testing closed auctions 0
Total auctionsHandle 1
No waiting auctions found
Finished checking day: 12/08/2021 Total auctions now: 45
testing closed auctions 0
Total auctionsHandle 9
Total auctionsHandle 9
Finished checking day: 12/09/2021 Total auctions now: 53
testing closed auctions 0
Total auctionsHandle 11
Total auctionsHandle 11
Total auctionsHandle 2
Finished checking day: 12/10/2021 Total auctions now: 58
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/14/2021 Total auctions now: 58
No closed auctions found
Total auctionsHandle 3
Finished checking day: 12/15/2021 Total auctions now: 61
No closed auctions found
Total auctionsHandle 2
Finished checking day: 12/16/2021 Total auctions now: 62
No closed auctions found
Total auctionsHandle 5
Finished checking day: 12/17/2021 Total auctions now: 64
testing closed auctions 0
Total auctionsHandle 7
Total auctionsHandle 7
Finished checking day: 12/20/2021 Total auctions now: 65
No closed auctions found
Total auctionsHandle 2
Finished checking day: 12/22/2021 Total auctions now: 65
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/27/2021 Total auctions now: 65
Finished checking day: 12/28/2021 Total auctions now: 65
No closed auctions found
Total auctionsHandle 3
Finished checking day: 12/29/2021 Total auctions now: 65
No closed auctions found
Total auctionsHandle 1
Finished checking day: 12/30/2021 Total auctions now: 65
Total auctions 65

Terminal will be reused by tasks, press any key to close it.
```

**Comment by aarmora** [comment]
@arthurbrazil Good call. I changed it back to Miami.

The other part is just logging that's confusing. I just removed that line so now it'll only say total auctions after each day.

Out of curiosity, are you yourself doing some real estate investing?

**Comment by arthurbrazil** [comment]
Just getting into it. I have some cash and 'Im looking to buy a property in
my area to rent.
